### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by justinjohn0306** [hiibolt/igait-openpose#1]
<img width="1190" alt="image" src="https://github.com/igait-niu/igait-openpose/assets/34035011/7595abde-ccba-4d55-b40c-582ca8c97c3d">

**Comment by hiibolt** [comment]
Hello!

You are not using our version of OpenPose, as far as I can tell.

Please pull it in the following manner:
```bash
docker pull ghcr.io/hiibolt/igait-openpose
```

Then, start it with the following command:
```bash
docker run -it --rm --gpus all --security-opt=label=disable ghcr.io/hiibolt/igait-openpose
```

Running an example inference:
```bash
./build/examples/openpose/openpose.bin --image_dir /openpose/examples/media --display 0 --write_images /output_images
```

Please note that in order for this to work, you will need to have the [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) installed.

**Comment by justinjohn0306** [comment]
> Hello!
> 
> You are not using our version of OpenPose, as far as I can tell.
> 
> Please pull it in the following manner:
> 
> ```shell
> docker pull ghcr.io/hiibolt/igait-openpose
> ```
> 
> Then, start it with the following command:
> 
> ```shell
> docker run -it --rm --gpus all --security-opt=label=disable ghcr.io/hiibolt/igait-openpose
> ```
> 
> Running an example inference:
> 
> ```shell
> ./build/examples/openpose/openpose.bin --image_dir /openpose/examples/media --display 0 --write_images /output_images
> ```
> 
> Please note that in order for this to work, you will need to have the [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) installed.

Pretty sure I did install this version of openpose and I do have Nvidia Container Toolkit installed via WSL2. I'm on Windows btw.

**Comment by hiibolt** [comment]
No, the command that you ran was `docker run ... openpose:latest`, which would mean it's searching the Docker Hub, not GHCR. 

Please try with our copy, and let us know how it goes!
